### ISSUE TITLE
Do not use I in articles

### ISSUE THREAD

**Issue by Emma-Song** [zilliztech/arctern-bootcamp#11]
Should talk to readers in the articles, so we should use "you" to describe the readers, and "we" to decribe us.

For example,

original: 数据过滤这一步十分重要，它可以保证**我**后期的数据分析结果有效。接下来我们将根据交易额和直线距离分析出租车的运营情况。
changed: 数据过滤这一步十分重要，它可以保证后期的数据分析结果有效。接下来我们将根据交易额和直线距离分析出租车的运营情况。

**Comment by shiyu22** [comment]
Done
