### ISSUE TITLE
Should add an introduction in README

### ISSUE THREAD

**Issue by Emma-Song** [zilliztech/arctern-bootcamp#7]
**Position:** Readme.md
**Issue:** The following list lacks an introduction. It is a little abrupt in the context.

* 强大的时空分析能力，Arctern 提供标准 OGC 地理空间数据处理接口、多种位置信息处理算法和时空分析模型。
* 基于 SQL 的数据分析交互。借助服务器端渲染技术，为时空数据分析提供高效、清晰的结果呈现方案。

**Comment by shiyu22** [comment]
Done

**Comment by shiyu22** [comment]
Done
